# Omarchy theme for mako (generated by omarchy-theme-set-templates).
# mako has no include directive, so this is the whole config.
# omarchy-theme-set-mako symlinks ~/.config/mako/config to the rendered
# copy in ~/.local/state/omarchy/current/theme/mako.ini and reloads mako.

font=Liberation Sans 11
width=420
height=110
margin=10
padding=10
border-size=2
border-radius=0
max-icon-size=32
default-timeout=5000
anchor=top-right

background-color={{ background }}
text-color={{ foreground }}
border-color={{ gradient_start hyprland_active_border accent }}
progress-color=over {{ selection }}

[urgency=low]
text-color={{ muted }}
border-color={{ gradient_start hyprland_inactive_border muted }}

[urgency=critical]
border-color={{ red }}
default-timeout=0

[mode=do-not-disturb]
invisible=1
