# Omarchy theme colors for sway (generated by omarchy-theme-set-templates).
# The sway config picks this up via:
#   include ~/.local/state/omarchy/current/theme/sway*

set $omarchy_active_border {{ gradient_start hyprland_active_border accent }}
set $omarchy_inactive_border {{ gradient_start hyprland_inactive_border muted }}

# class                 border                   background       text             indicator                child_border
client.focused          $omarchy_active_border   {{ background }} {{ foreground }} {{ accent }}             $omarchy_active_border
client.focused_inactive $omarchy_inactive_border {{ background }} {{ foreground }} $omarchy_inactive_border $omarchy_inactive_border
client.unfocused        $omarchy_inactive_border {{ background }} {{ muted }}      $omarchy_inactive_border $omarchy_inactive_border
client.urgent           {{ red }}                {{ background }} {{ foreground }} {{ red }}                {{ red }}
client.placeholder      {{ background }}         {{ background }} {{ muted }}      {{ background }}         {{ background }}
client.background       {{ background }}
