/* Omarchy theme colors for waybar (generated by omarchy-theme-set-templates).
 * Imported by ~/.config/waybar/style.css from
 * ~/.local/state/omarchy/current/theme/waybar.css.
 * Only @define-color definitions belong here; layout lives in style.css. */

@define-color background {{ background }};
@define-color dark_background {{ dark_background }};
@define-color darker_background {{ darker_background }};
@define-color lighter_background {{ lighter_background }};

@define-color foreground {{ foreground }};
@define-color dark_foreground {{ dark_foreground }};
@define-color light_foreground {{ light_foreground }};
@define-color bright_foreground {{ bright_foreground }};

@define-color accent {{ accent }};
@define-color muted {{ muted }};
@define-color selection {{ selection }};
@define-color selection_foreground {{ selection_foreground }};

@define-color active_border {{ gradient_start hyprland_active_border accent }};
@define-color inactive_border {{ gradient_start hyprland_inactive_border muted }};
@define-color urgent {{ red }};

@define-color red {{ red }};
@define-color green {{ green }};
@define-color yellow {{ yellow }};
@define-color blue {{ blue }};
@define-color magenta {{ magenta }};
@define-color cyan {{ cyan }};
@define-color orange {{ orange }};

@define-color bright_red {{ bright_red }};
@define-color bright_green {{ bright_green }};
@define-color bright_yellow {{ bright_yellow }};
@define-color bright_blue {{ bright_blue }};
@define-color bright_magenta {{ bright_magenta }};
@define-color bright_cyan {{ bright_cyan }};
